# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @useDynLib RepertoireUtils
#' @importFrom Rcpp sourceCpp
permute_diversity <- function(left, right, iterations, use_gini, use_hill, seed, stream) {
    .Call('_RepertoireUtils_permute_diversity', PACKAGE = 'RepertoireUtils', left, right, iterations, use_gini, use_hill, seed, stream)
}

